/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AAnchorLink: typeof import('ant-design-vue/es')['AnchorLink']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    CheckboxRadio: typeof import('./src/components/CheckboxRadio.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAnchor: typeof import('ant-design-vue/es')['Anchor']
  const AAnchorLink: typeof import('ant-design-vue/es')['AnchorLink']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACard: typeof import('ant-design-vue/es')['Card']
  const ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
  const ACol: typeof import('ant-design-vue/es')['Col']
  const AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
  const ADropdown: typeof import('ant-design-vue/es')['Dropdown']
  const AEmpty: typeof import('ant-design-vue/es')['Empty']
  const AForm: typeof import('ant-design-vue/es')['Form']
  const AFormItem: typeof import('ant-design-vue/es')['FormItem']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
  const AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
  const AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
  const ALayout: typeof import('ant-design-vue/es')['Layout']
  const ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
  const AModal: typeof import('ant-design-vue/es')['Modal']
  const ARow: typeof import('ant-design-vue/es')['Row']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
  const ASpace: typeof import('ant-design-vue/es')['Space']
  const ASpin: typeof import('ant-design-vue/es')['Spin']
  const ATable: typeof import('ant-design-vue/es')['Table']
  const ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
  const ATag: typeof import('ant-design-vue/es')['Tag']
  const AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
  const CheckboxRadio: typeof import('./src/components/CheckboxRadio.vue')['default']
  const GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}